// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.12
// source: blockchain/indexing.proto

package blockchain_messages

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Indexing struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SegmentHash []byte `protobuf:"bytes,1,opt,name=SegmentHash,proto3" json:"SegmentHash,omitempty"`
	LogicalTime int64  `protobuf:"varint,2,opt,name=LogicalTime,proto3" json:"LogicalTime,omitempty"`
	Time        int64  `protobuf:"varint,3,opt,name=Time,proto3" json:"Time,omitempty"`
	OnTree      bool   `protobuf:"varint,4,opt,name=OnTree,proto3" json:"OnTree,omitempty"`
	OnTrunk     bool   `protobuf:"varint,5,opt,name=OnTrunk,proto3" json:"OnTrunk,omitempty"`
}

func (x *Indexing) Reset() {
	*x = Indexing{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blockchain_indexing_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Indexing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Indexing) ProtoMessage() {}

func (x *Indexing) ProtoReflect() protoreflect.Message {
	mi := &file_blockchain_indexing_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Indexing.ProtoReflect.Descriptor instead.
func (*Indexing) Descriptor() ([]byte, []int) {
	return file_blockchain_indexing_proto_rawDescGZIP(), []int{0}
}

func (x *Indexing) GetSegmentHash() []byte {
	if x != nil {
		return x.SegmentHash
	}
	return nil
}

func (x *Indexing) GetLogicalTime() int64 {
	if x != nil {
		return x.LogicalTime
	}
	return 0
}

func (x *Indexing) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *Indexing) GetOnTree() bool {
	if x != nil {
		return x.OnTree
	}
	return false
}

func (x *Indexing) GetOnTrunk() bool {
	if x != nil {
		return x.OnTrunk
	}
	return false
}

var File_blockchain_indexing_proto protoreflect.FileDescriptor

var file_blockchain_indexing_proto_rawDesc = []byte{
	0x0a, 0x19, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2f, 0x69, 0x6e, 0x64,
	0x65, 0x78, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x62, 0x6c, 0x6f,
	0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x22, 0x94, 0x01, 0x0a, 0x08, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x69, 0x6e, 0x67, 0x12, 0x20, 0x0a,
	0x0b, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x48, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x0b, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x48, 0x61, 0x73, 0x68, 0x12,
	0x20, 0x0a, 0x0b, 0x4c, 0x6f, 0x67, 0x69, 0x63, 0x61, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x4c, 0x6f, 0x67, 0x69, 0x63, 0x61, 0x6c, 0x54, 0x69, 0x6d,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x04, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x4f, 0x6e, 0x54, 0x72, 0x65, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x4f, 0x6e, 0x54, 0x72, 0x65, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x4f, 0x6e, 0x54, 0x72, 0x75, 0x6e, 0x6b, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x4f, 0x6e, 0x54, 0x72, 0x75, 0x6e, 0x6b, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_blockchain_indexing_proto_rawDescOnce sync.Once
	file_blockchain_indexing_proto_rawDescData = file_blockchain_indexing_proto_rawDesc
)

func file_blockchain_indexing_proto_rawDescGZIP() []byte {
	file_blockchain_indexing_proto_rawDescOnce.Do(func() {
		file_blockchain_indexing_proto_rawDescData = protoimpl.X.CompressGZIP(file_blockchain_indexing_proto_rawDescData)
	})
	return file_blockchain_indexing_proto_rawDescData
}

var file_blockchain_indexing_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_blockchain_indexing_proto_goTypes = []interface{}{
	(*Indexing)(nil), // 0: blockchain_messages.Indexing
}
var file_blockchain_indexing_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_blockchain_indexing_proto_init() }
func file_blockchain_indexing_proto_init() {
	if File_blockchain_indexing_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_blockchain_indexing_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Indexing); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_blockchain_indexing_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_blockchain_indexing_proto_goTypes,
		DependencyIndexes: file_blockchain_indexing_proto_depIdxs,
		MessageInfos:      file_blockchain_indexing_proto_msgTypes,
	}.Build()
	File_blockchain_indexing_proto = out.File
	file_blockchain_indexing_proto_rawDesc = nil
	file_blockchain_indexing_proto_goTypes = nil
	file_blockchain_indexing_proto_depIdxs = nil
}
